### ISSUE TITLE
Compile error: undefined reference to `__gthrw___pthread_key_create

### ISSUE THREAD

**Issue by mskerritt** [microsoft/diskspd-for-linux#8]
This is an error I got trying to compile on Centos 7.5. After looking it up, this link helped me out:

https://stackoverflow.com/questions/27257655/undefined-reference-to-gthrw-pthread-key-createunsigned-int-void-voi

As it recommends, putting "include <thread>" in options.cc resolved the issue.
Figured I would pass this along to you.

There were other errors, too:

src/posix_aio.cc:251:19: error: no matching function for call to ‘std::vector<aiocb*>::erase(__gnu_cxx::__normal_iterator<aiocb* const*, std::vector<aiocb*> >&)’
      vec->erase(it);

and:

src/result_formatter.cc: In member function ‘virtual void diskspd::ResultFormatterText::output_results(const diskspd::Profile&)’:
src/result_formatter.cc:107:48: error: variable-sized object ‘cpu_usage_totals’ may not be initialized
    double cpu_usage_totals[num_cpu_fields] = {0};

But I was able to work around them with hacks...
Thanks,
-mike

**Comment by peter9370** [comment]
Many thanks for that - putting "#include <thread>" in options.cc fixed it for me also.
